# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calls_pb2 as calls__pb2


class recorderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ingestRecord = channel.unary_unary(
                '/recorder/ingestRecord',
                request_serializer=calls__pb2.callerRecord.SerializeToString,
                response_deserializer=calls__pb2.ackRecord.FromString,
                )


class recorderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ingestRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_recorderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ingestRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.ingestRecord,
                    request_deserializer=calls__pb2.callerRecord.FromString,
                    response_serializer=calls__pb2.ackRecord.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recorder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class recorder(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ingestRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recorder/ingestRecord',
            calls__pb2.callerRecord.SerializeToString,
            calls__pb2.ackRecord.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
