# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calls.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61lls.proto\" \n\x0c\x63\x61llerRecord\x12\x10\n\x08\x46ullName\x18\x01 \x01(\t\"\x1c\n\tackRecord\x12\x0f\n\x07message\x18\x01 \x01(\t25\n\x08recorder\x12)\n\x0cingestRecord\x12\r.callerRecord\x1a\n.ackRecordb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calls_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALLERRECORD._serialized_start=15
  _CALLERRECORD._serialized_end=47
  _ACKRECORD._serialized_start=49
  _ACKRECORD._serialized_end=77
  _RECORDER._serialized_start=79
  _RECORDER._serialized_end=132
# @@protoc_insertion_point(module_scope)
